services:
  app:
    image: mafia:dev
    container_name: mafia-app
    ports:
      - "8001:3000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - my-network

  redis:
    image: redis:8
    container_name: redis
    networks:
      - my-network

networks:
  my-network: