name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t backend-app:latest .

      - name: Save Docker image to tar file
        run: |
          docker save backend-app:latest -o backend.tar
          chmod 644 backend.tar

      - name: Upload backend image
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          rsync -avz -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" backend.tar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/opt/mafia/backend-deploy/backend.tar

      - name: Deploy backend on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            bash /opt/mafia/backend-deploy/deploy_backend.sh

